"""
MODULE: ANL-003
FILE: ANL-003-001
Module Name: Liquidity Engine
Version: 0.9.1
Purpose: Detects read-only liquidity pools, liquidity sweeps, and inducement candidates from validated candles and confirmed market structure.
Dependencies: datetime, logging, sentinel_ai.config.config_schema, sentinel_ai.models.liquidity, sentinel_ai.models.market, sentinel_ai.models.market_structure
Change History:
- 0.9.0: Added liquidity engine foundation without prediction or trading execution.
- 0.9.1: Added bounded liquidity pool segment timing and reduced overlay noise.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from sentinel_ai.config.config_schema import LiquidityConfig
from sentinel_ai.models.liquidity import LiquidityPool, LiquiditySnapshot, LiquiditySweep
from sentinel_ai.models.market import MarketBar, MarketDataSnapshot
from sentinel_ai.models.market_structure import MarketStructureSnapshot, SwingPoint


class LiquidityEngine:
    """Analyze validated candles and confirmed structure for liquidity context only."""

    def __init__(self, config: LiquidityConfig, logger: logging.Logger) -> None:
        """Initialize the liquidity engine using validated configuration and logging."""
        self._config = config
        self._logger = logger
        self._latest_snapshot: LiquiditySnapshot | None = None

    @property
    def latest_snapshot(self) -> LiquiditySnapshot | None:
        """Return the latest liquidity snapshot generated by this engine."""
        return self._latest_snapshot

    def analyze(
        self,
        market_snapshot: MarketDataSnapshot,
        structure_snapshot: MarketStructureSnapshot,
    ) -> LiquiditySnapshot:
        """Analyze market and structure snapshots and return read-only liquidity context."""
        candles = self._select_analysis_candles(market_snapshot)
        if not candles:
            raise ValueError("Liquidity analysis requires at least one validated candle.")
        if not self._config.enabled:
            snapshot = self._build_disabled_snapshot(market_snapshot, len(candles))
            self._latest_snapshot = snapshot
            return snapshot

        relevant_swings = self._select_relevant_swings(structure_snapshot, candles)
        sweeps = self._detect_sweeps(candles, relevant_swings)
        pools = self._build_liquidity_pools(relevant_swings, sweeps, candles[-1].close, candles[-1].time)
        latest_bullish_sweep = self._latest_directional_sweep(sweeps, "BULLISH")
        latest_bearish_sweep = self._latest_directional_sweep(sweeps, "BEARISH")
        summary = self._build_summary(pools, sweeps, latest_bullish_sweep, latest_bearish_sweep, len(candles))
        snapshot = LiquiditySnapshot(
            symbol=market_snapshot.symbol,
            timeframe=market_snapshot.timeframe,
            pools=pools,
            sweeps=sweeps,
            latest_bullish_sweep=latest_bullish_sweep,
            latest_bearish_sweep=latest_bearish_sweep,
            generated_at=datetime.now(timezone.utc),
            analyzed_candle_count=len(candles),
            summary=summary,
        )
        self._latest_snapshot = snapshot
        self._logger.debug("Liquidity analyzed for %s %s: %s", market_snapshot.symbol, market_snapshot.timeframe, summary)
        return snapshot

    def _select_analysis_candles(self, market_snapshot: MarketDataSnapshot) -> tuple[MarketBar, ...]:
        """Return the configured candle lookback used by the liquidity engine."""
        lookback = int(self._config.lookback_candles)
        return tuple(market_snapshot.candles[-lookback:])

    @staticmethod
    def _select_relevant_swings(
        structure_snapshot: MarketStructureSnapshot,
        candles: tuple[MarketBar, ...],
    ) -> tuple[SwingPoint, ...]:
        """Return confirmed swings inside the selected liquidity lookback window."""
        earliest_time = candles[0].time
        swings = tuple(
            swing
            for swing in (*structure_snapshot.swing_highs, *structure_snapshot.swing_lows)
            if swing.time >= earliest_time
        )
        return tuple(sorted(swings, key=lambda swing: swing.time))

    def _detect_sweeps(
        self,
        candles: tuple[MarketBar, ...],
        swings: tuple[SwingPoint, ...],
    ) -> tuple[LiquiditySweep, ...]:
        """Detect confirmed liquidity sweeps after each reference swing forms."""
        sweeps: list[LiquiditySweep] = []
        swept_references: set[tuple[str, datetime, float]] = set()
        buffer_price = float(self._config.sweep_buffer_price)
        candle_by_time = {candle.time: index for index, candle in enumerate(candles)}
        for swing in swings:
            swing_index = candle_by_time.get(swing.time)
            if swing_index is None:
                continue
            for candle in candles[swing_index + 1 :]:
                if swing.is_high and candle.high > swing.price + buffer_price and candle.close < swing.price:
                    reference_key = ("BUY_SIDE", swing.time, float(swing.price))
                    if reference_key not in swept_references:
                        sweeps.append(
                            LiquiditySweep(
                                direction="BEARISH",
                                swept_side="BUY_SIDE",
                                reference_price=swing.price,
                                reference_time=swing.time,
                                swept_at=candle.time,
                                wick_price=candle.high,
                                close_price=candle.close,
                                label="BSL sweep",
                            )
                        )
                        swept_references.add(reference_key)
                    break
                if swing.is_low and candle.low < swing.price - buffer_price and candle.close > swing.price:
                    reference_key = ("SELL_SIDE", swing.time, float(swing.price))
                    if reference_key not in swept_references:
                        sweeps.append(
                            LiquiditySweep(
                                direction="BULLISH",
                                swept_side="SELL_SIDE",
                                reference_price=swing.price,
                                reference_time=swing.time,
                                swept_at=candle.time,
                                wick_price=candle.low,
                                close_price=candle.close,
                                label="SSL sweep",
                            )
                        )
                        swept_references.add(reference_key)
                    break
        limited_sweeps = sorted(sweeps, key=lambda sweep: sweep.swept_at)[-int(self._config.max_chart_sweeps) :]
        return tuple(limited_sweeps)

    def _build_liquidity_pools(
        self,
        swings: tuple[SwingPoint, ...],
        sweeps: tuple[LiquiditySweep, ...],
        latest_close: float,
        latest_candle_time: datetime,
    ) -> tuple[LiquidityPool, ...]:
        """Build active and swept liquidity pools from confirmed swing points with bounded chart timing."""
        sweep_by_reference = {
            (sweep.swept_side, sweep.reference_time, float(sweep.reference_price)): sweep
            for sweep in sweeps
        }
        pools: list[LiquidityPool] = []
        inducement_distance = float(self._config.inducement_distance_price)
        for swing in swings:
            side = "BUY_SIDE" if swing.is_high else "SELL_SIDE"
            label = "BSL" if swing.is_high else "SSL"
            distance = abs(float(latest_close) - float(swing.price))
            reference_key = (side, swing.time, float(swing.price))
            matching_sweep = sweep_by_reference.get(reference_key)
            swept = matching_sweep is not None
            inducement_candidate = not swept and (inducement_distance <= 0 or distance <= inducement_distance)
            pools.append(
                LiquidityPool(
                    side=side,
                    price=float(swing.price),
                    reference_time=swing.time,
                    reference_kind=swing.kind,
                    end_time=matching_sweep.swept_at if matching_sweep is not None else latest_candle_time,
                    swept=swept,
                    inducement_candidate=inducement_candidate,
                    distance_from_price=distance,
                    label=label,
                )
            )
        pools.sort(key=lambda pool: (pool.swept, pool.distance_from_price, -pool.reference_time.timestamp()), reverse=False)
        return tuple(pools[: int(self._config.max_chart_pools)])

    @staticmethod
    def _latest_directional_sweep(sweeps: tuple[LiquiditySweep, ...], direction: str) -> LiquiditySweep | None:
        """Return the latest sweep for a requested direction."""
        matching = tuple(sweep for sweep in sweeps if sweep.direction == direction)
        if not matching:
            return None
        return matching[-1]

    @staticmethod
    def _build_summary(
        pools: tuple[LiquidityPool, ...],
        sweeps: tuple[LiquiditySweep, ...],
        latest_bullish_sweep: LiquiditySweep | None,
        latest_bearish_sweep: LiquiditySweep | None,
        analyzed_candle_count: int,
    ) -> str:
        """Build a concise liquidity summary for GUI display and logs."""
        active_buy_side = sum(1 for pool in pools if pool.is_buy_side and not pool.swept)
        active_sell_side = sum(1 for pool in pools if pool.is_sell_side and not pool.swept)
        bullish_text = "no bullish liquidity sweep"
        if latest_bullish_sweep is not None:
            bullish_text = f"bullish sweep below {latest_bullish_sweep.reference_price:.2f}"
        bearish_text = "no bearish liquidity sweep"
        if latest_bearish_sweep is not None:
            bearish_text = f"bearish sweep above {latest_bearish_sweep.reference_price:.2f}"
        inducement_count = sum(1 for pool in pools if pool.inducement_candidate)
        return (
            f"Liquidity: BSL {active_buy_side}, SSL {active_sell_side}; "
            f"{bullish_text}; {bearish_text}; inducements {inducement_count}; "
            f"sweeps {len(sweeps)}; candles {analyzed_candle_count}"
        )

    @staticmethod
    def _build_disabled_snapshot(market_snapshot: MarketDataSnapshot, analyzed_candle_count: int) -> LiquiditySnapshot:
        """Build a neutral snapshot when the liquidity engine is disabled."""
        return LiquiditySnapshot(
            symbol=market_snapshot.symbol,
            timeframe=market_snapshot.timeframe,
            pools=(),
            sweeps=(),
            latest_bullish_sweep=None,
            latest_bearish_sweep=None,
            generated_at=datetime.now(timezone.utc),
            analyzed_candle_count=analyzed_candle_count,
            summary="Liquidity engine disabled by configuration.",
        )
