"""
MODULE: ANL-001
FILE: ANL-001-001
Module Name: Market Structure Engine
Version: 0.7.0
Purpose: Detects confirmed swing highs, swing lows, structural bias, and basic break-of-structure conditions from validated candles.
Dependencies: datetime, logging, sentinel_ai.config.config_schema, sentinel_ai.models.market, sentinel_ai.models.market_structure
Change History:
- 0.7.0: Added read-only market structure engine foundation without prediction or trading execution.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from sentinel_ai.config.config_schema import MarketStructureConfig
from sentinel_ai.models.market import MarketBar, MarketDataSnapshot
from sentinel_ai.models.market_structure import MarketStructureSnapshot, StructureBreak, SwingPoint


class MarketStructureEngine:
    """Analyze validated candles for confirmed market structure without creating trade predictions."""

    def __init__(self, config: MarketStructureConfig, logger: logging.Logger) -> None:
        """Initialize the engine using validated configuration and application logging."""
        self._config = config
        self._logger = logger
        self._latest_snapshot: MarketStructureSnapshot | None = None

    @property
    def latest_snapshot(self) -> MarketStructureSnapshot | None:
        """Return the latest market-structure snapshot generated by this engine."""
        return self._latest_snapshot

    def analyze(self, market_snapshot: MarketDataSnapshot) -> MarketStructureSnapshot:
        """Analyze a market data snapshot and return a read-only structure snapshot."""
        candles = self._select_analysis_candles(market_snapshot)
        if not self._config.enabled:
            structure_snapshot = self._build_disabled_snapshot(market_snapshot, len(candles))
            self._latest_snapshot = structure_snapshot
            return structure_snapshot

        swing_highs, swing_lows = self._detect_swing_points(candles)
        latest_break = self._detect_latest_structure_break(candles, swing_highs, swing_lows)
        bias = self._determine_bias(swing_highs, swing_lows, latest_break)
        summary = self._build_summary(bias, swing_highs, swing_lows, latest_break, len(candles))
        structure_snapshot = MarketStructureSnapshot(
            symbol=market_snapshot.symbol,
            timeframe=market_snapshot.timeframe,
            bias=bias,
            swing_highs=swing_highs,
            swing_lows=swing_lows,
            latest_break=latest_break,
            analyzed_candle_count=len(candles),
            generated_at=datetime.now(timezone.utc),
            summary=summary,
        )
        self._latest_snapshot = structure_snapshot
        self._logger.debug("Market structure analyzed for %s %s: %s", market_snapshot.symbol, market_snapshot.timeframe, summary)
        return structure_snapshot

    def _select_analysis_candles(self, market_snapshot: MarketDataSnapshot) -> tuple[MarketBar, ...]:
        """Return the configured candle lookback used by the structure engine."""
        lookback = int(self._config.lookback_candles)
        candles = market_snapshot.candles[-lookback:]
        return tuple(candles)

    def _detect_swing_points(self, candles: tuple[MarketBar, ...]) -> tuple[tuple[SwingPoint, ...], tuple[SwingPoint, ...]]:
        """Detect confirmed swing highs and lows using a symmetric candle window."""
        window = int(self._config.swing_window)
        if len(candles) < window * 2 + 1:
            return (), ()

        swing_highs: list[SwingPoint] = []
        swing_lows: list[SwingPoint] = []
        for index in range(window, len(candles) - window):
            candle = candles[index]
            left_side = candles[index - window : index]
            right_side = candles[index + 1 : index + window + 1]
            surrounding = (*left_side, *right_side)
            if self._is_swing_high(candle, surrounding):
                candidate = SwingPoint(kind="HIGH", time=candle.time, price=candle.high, candle_index=index)
                if self._is_far_enough_from_previous(candidate, swing_highs):
                    swing_highs.append(candidate)
            if self._is_swing_low(candle, surrounding):
                candidate = SwingPoint(kind="LOW", time=candle.time, price=candle.low, candle_index=index)
                if self._is_far_enough_from_previous(candidate, swing_lows):
                    swing_lows.append(candidate)

        return tuple(swing_highs), tuple(swing_lows)

    @staticmethod
    def _is_swing_high(candle: MarketBar, surrounding: tuple[MarketBar, ...]) -> bool:
        """Return True when the candle high is strictly above surrounding highs."""
        return all(candle.high > other.high for other in surrounding)

    @staticmethod
    def _is_swing_low(candle: MarketBar, surrounding: tuple[MarketBar, ...]) -> bool:
        """Return True when the candle low is strictly below surrounding lows."""
        return all(candle.low < other.low for other in surrounding)

    def _is_far_enough_from_previous(self, candidate: SwingPoint, previous_swings: list[SwingPoint]) -> bool:
        """Return True when a candidate swing is not a near-duplicate of the prior same-side swing."""
        minimum_distance = float(self._config.minimum_swing_distance_price)
        if minimum_distance <= 0 or not previous_swings:
            return True
        return abs(candidate.price - previous_swings[-1].price) >= minimum_distance

    @staticmethod
    def _detect_latest_structure_break(
        candles: tuple[MarketBar, ...],
        swing_highs: tuple[SwingPoint, ...],
        swing_lows: tuple[SwingPoint, ...],
    ) -> StructureBreak | None:
        """Detect the latest close-based break of the most recent confirmed swing level."""
        latest_candle = candles[-1] if candles else None
        if latest_candle is None:
            return None

        latest_high = swing_highs[-1] if swing_highs else None
        latest_low = swing_lows[-1] if swing_lows else None
        if latest_high is not None and latest_candle.close > latest_high.price:
            return StructureBreak(
                direction="BULLISH",
                reference_price=latest_high.price,
                reference_time=latest_high.time,
                broken_at=latest_candle.time,
                close_price=latest_candle.close,
            )
        if latest_low is not None and latest_candle.close < latest_low.price:
            return StructureBreak(
                direction="BEARISH",
                reference_price=latest_low.price,
                reference_time=latest_low.time,
                broken_at=latest_candle.time,
                close_price=latest_candle.close,
            )
        return None

    @staticmethod
    def _determine_bias(
        swing_highs: tuple[SwingPoint, ...],
        swing_lows: tuple[SwingPoint, ...],
        latest_break: StructureBreak | None,
    ) -> str:
        """Determine structural bias from swing sequence and confirmed close-based break."""
        if latest_break is not None:
            return latest_break.direction
        if len(swing_highs) < 2 or len(swing_lows) < 2:
            return "INSUFFICIENT_STRUCTURE"

        previous_high, latest_high = swing_highs[-2], swing_highs[-1]
        previous_low, latest_low = swing_lows[-2], swing_lows[-1]
        higher_high = latest_high.price > previous_high.price
        higher_low = latest_low.price > previous_low.price
        lower_high = latest_high.price < previous_high.price
        lower_low = latest_low.price < previous_low.price

        if higher_high and higher_low:
            return "BULLISH"
        if lower_high and lower_low:
            return "BEARISH"
        return "RANGING"

    @staticmethod
    def _build_summary(
        bias: str,
        swing_highs: tuple[SwingPoint, ...],
        swing_lows: tuple[SwingPoint, ...],
        latest_break: StructureBreak | None,
        analyzed_candle_count: int,
    ) -> str:
        """Build a concise status summary for GUI display and logs."""
        latest_high = swing_highs[-1].price if swing_highs else None
        latest_low = swing_lows[-1].price if swing_lows else None
        high_text = f"last swing high {latest_high:.2f}" if latest_high is not None else "no confirmed swing high"
        low_text = f"last swing low {latest_low:.2f}" if latest_low is not None else "no confirmed swing low"
        break_text = "no close-based BOS"
        if latest_break is not None:
            level_word = "above" if latest_break.is_bullish else "below"
            break_text = f"{latest_break.direction.lower()} BOS {level_word} {latest_break.reference_price:.2f}"
        return f"{bias}; {high_text}; {low_text}; {break_text}; analyzed {analyzed_candle_count} candles"

    @staticmethod
    def _build_disabled_snapshot(market_snapshot: MarketDataSnapshot, analyzed_candle_count: int) -> MarketStructureSnapshot:
        """Build a neutral snapshot when the market structure engine is disabled."""
        return MarketStructureSnapshot(
            symbol=market_snapshot.symbol,
            timeframe=market_snapshot.timeframe,
            bias="DISABLED",
            swing_highs=(),
            swing_lows=(),
            latest_break=None,
            analyzed_candle_count=analyzed_candle_count,
            generated_at=datetime.now(timezone.utc),
            summary="Market structure engine disabled by configuration.",
        )
