"""
MODULE: ANL-002
FILE: ANL-002-001
Module Name: Support and Resistance Engine
Version: 0.8.0
Purpose: Detects ranked support and resistance zones from confirmed market-structure swing points.
Dependencies: datetime, logging, statistics, sentinel_ai.config.config_schema, sentinel_ai.models.market, sentinel_ai.models.market_structure, sentinel_ai.models.support_resistance
Change History:
- 0.8.0: Added read-only support/resistance zone engine foundation without prediction or trading execution.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone

from sentinel_ai.config.config_schema import SupportResistanceConfig
from sentinel_ai.models.market import MarketBar, MarketDataSnapshot
from sentinel_ai.models.market_structure import MarketStructureSnapshot, SwingPoint
from sentinel_ai.models.support_resistance import SupportResistanceSnapshot, SupportResistanceZone


@dataclass
class _MutableZone:
    """Accumulate related swing prices before converting them into an immutable zone."""

    kind: str
    prices: list[float]
    times: list[datetime]

    @property
    def midpoint(self) -> float:
        """Return the current average price for this accumulating zone."""
        return sum(self.prices) / len(self.prices)

    @property
    def touch_count(self) -> int:
        """Return how many swing touches are grouped into this zone."""
        return len(self.prices)

    def add(self, swing: SwingPoint) -> None:
        """Add one swing point to this accumulating zone."""
        self.prices.append(float(swing.price))
        self.times.append(swing.time)


class SupportResistanceEngine:
    """Analyze confirmed market-structure swings for ranked support and resistance zones."""

    def __init__(self, config: SupportResistanceConfig, logger: logging.Logger) -> None:
        """Initialize the engine using validated configuration and application logging."""
        self._config = config
        self._logger = logger
        self._latest_snapshot: SupportResistanceSnapshot | None = None

    @property
    def latest_snapshot(self) -> SupportResistanceSnapshot | None:
        """Return the latest support/resistance snapshot generated by this engine."""
        return self._latest_snapshot

    def analyze(
        self,
        market_snapshot: MarketDataSnapshot,
        structure_snapshot: MarketStructureSnapshot,
    ) -> SupportResistanceSnapshot:
        """Analyze validated market and structure snapshots and return read-only support/resistance context."""
        candles = self._select_analysis_candles(market_snapshot)
        latest_close = self._latest_close(candles)
        relevant_swings = self._select_relevant_swings(structure_snapshot, candles)
        zone_tolerance = self._resolve_zone_tolerance(candles)

        if not self._config.enabled:
            snapshot = self._build_disabled_snapshot(market_snapshot, len(relevant_swings), zone_tolerance)
            self._latest_snapshot = snapshot
            return snapshot

        support_zones = self._build_ranked_zones(
            kind="SUPPORT",
            swings=tuple(swing for swing in relevant_swings if swing.is_low),
            zone_tolerance=zone_tolerance,
            latest_close=latest_close,
        )
        resistance_zones = self._build_ranked_zones(
            kind="RESISTANCE",
            swings=tuple(swing for swing in relevant_swings if swing.is_high),
            zone_tolerance=zone_tolerance,
            latest_close=latest_close,
        )
        nearest_support = self._nearest_support(support_zones, latest_close)
        nearest_resistance = self._nearest_resistance(resistance_zones, latest_close)
        summary = self._build_summary(nearest_support, nearest_resistance, len(relevant_swings), zone_tolerance)
        snapshot = SupportResistanceSnapshot(
            symbol=market_snapshot.symbol,
            timeframe=market_snapshot.timeframe,
            support_zones=support_zones,
            resistance_zones=resistance_zones,
            nearest_support=nearest_support,
            nearest_resistance=nearest_resistance,
            generated_at=datetime.now(timezone.utc),
            analyzed_swing_count=len(relevant_swings),
            zone_tolerance_price=zone_tolerance,
            summary=summary,
        )
        self._latest_snapshot = snapshot
        self._logger.debug("Support/resistance analyzed for %s %s: %s", market_snapshot.symbol, market_snapshot.timeframe, summary)
        return snapshot

    def _select_analysis_candles(self, market_snapshot: MarketDataSnapshot) -> tuple[MarketBar, ...]:
        """Return the configured candle lookback used by the support/resistance engine."""
        lookback = int(self._config.lookback_candles)
        return tuple(market_snapshot.candles[-lookback:])

    @staticmethod
    def _latest_close(candles: tuple[MarketBar, ...]) -> float:
        """Return the latest candle close price or raise a clear validation error."""
        if not candles:
            raise ValueError("Support/resistance analysis requires at least one validated candle.")
        return float(candles[-1].close)

    @staticmethod
    def _select_relevant_swings(
        structure_snapshot: MarketStructureSnapshot,
        candles: tuple[MarketBar, ...],
    ) -> tuple[SwingPoint, ...]:
        """Return structure swings that belong to the selected candle lookback window."""
        if not candles:
            return ()
        earliest_time = candles[0].time
        swings = tuple(
            swing
            for swing in (*structure_snapshot.swing_highs, *structure_snapshot.swing_lows)
            if swing.time >= earliest_time
        )
        return tuple(sorted(swings, key=lambda swing: swing.time))

    def _resolve_zone_tolerance(self, candles: tuple[MarketBar, ...]) -> float:
        """Return the zone grouping tolerance using ATR-derived width and configured minimum width."""
        atr = self._calculate_average_true_range(candles, int(self._config.atr_period))
        tolerance = atr * float(self._config.zone_atr_multiplier)
        return max(float(self._config.minimum_zone_width_price), tolerance)

    @staticmethod
    def _calculate_average_true_range(candles: tuple[MarketBar, ...], period: int) -> float:
        """Calculate a simple average true range from validated candles."""
        if len(candles) < 2:
            return 0.0
        ranges: list[float] = []
        start_index = max(1, len(candles) - max(1, period))
        for index in range(start_index, len(candles)):
            candle = candles[index]
            previous = candles[index - 1]
            true_range = max(
                float(candle.high) - float(candle.low),
                abs(float(candle.high) - float(previous.close)),
                abs(float(candle.low) - float(previous.close)),
            )
            ranges.append(true_range)
        if not ranges:
            return 0.0
        return sum(ranges) / len(ranges)

    def _build_ranked_zones(
        self,
        kind: str,
        swings: tuple[SwingPoint, ...],
        zone_tolerance: float,
        latest_close: float,
    ) -> tuple[SupportResistanceZone, ...]:
        """Group nearby swing prices into ranked immutable support/resistance zones."""
        raw_zones = self._group_swings_into_zones(kind, swings, zone_tolerance)
        minimum_touches = int(self._config.min_touch_count)
        ranked_zones = [
            self._to_zone(raw_zone, zone_tolerance, latest_close)
            for raw_zone in raw_zones
            if raw_zone.touch_count >= minimum_touches
        ]
        ranked_zones.sort(key=lambda zone: (-zone.strength_score, zone.distance_from_price, -zone.last_seen.timestamp()))
        limited_zones = ranked_zones[: int(self._config.max_chart_zones)]
        return tuple(
            SupportResistanceZone(
                kind=zone.kind,
                lower_price=zone.lower_price,
                upper_price=zone.upper_price,
                midpoint=zone.midpoint,
                touch_count=zone.touch_count,
                first_seen=zone.first_seen,
                last_seen=zone.last_seen,
                distance_from_price=zone.distance_from_price,
                strength_score=zone.strength_score,
                rank=index + 1,
            )
            for index, zone in enumerate(limited_zones)
        )

    @staticmethod
    def _group_swings_into_zones(
        kind: str,
        swings: tuple[SwingPoint, ...],
        zone_tolerance: float,
    ) -> list[_MutableZone]:
        """Group same-side swings into nearby support/resistance zone candidates."""
        zones: list[_MutableZone] = []
        for swing in sorted(swings, key=lambda item: item.price):
            matching_zone = next(
                (zone for zone in zones if abs(float(swing.price) - zone.midpoint) <= zone_tolerance),
                None,
            )
            if matching_zone is None:
                zones.append(_MutableZone(kind=kind, prices=[float(swing.price)], times=[swing.time]))
            else:
                matching_zone.add(swing)
        return zones

    @staticmethod
    def _to_zone(raw_zone: _MutableZone, zone_tolerance: float, latest_close: float) -> SupportResistanceZone:
        """Convert a mutable grouped zone into an immutable ranked-zone candidate."""
        lower_price = min(raw_zone.prices) - zone_tolerance / 2.0
        upper_price = max(raw_zone.prices) + zone_tolerance / 2.0
        midpoint = raw_zone.midpoint
        distance = 0.0 if lower_price <= latest_close <= upper_price else min(abs(latest_close - lower_price), abs(latest_close - upper_price))
        recency_score = max(raw_zone.times).timestamp() / 10000000000.0
        strength_score = raw_zone.touch_count * 10.0 + recency_score
        return SupportResistanceZone(
            kind=raw_zone.kind,
            lower_price=lower_price,
            upper_price=upper_price,
            midpoint=midpoint,
            touch_count=raw_zone.touch_count,
            first_seen=min(raw_zone.times),
            last_seen=max(raw_zone.times),
            distance_from_price=distance,
            strength_score=strength_score,
            rank=0,
        )

    @staticmethod
    def _nearest_support(zones: tuple[SupportResistanceZone, ...], latest_close: float) -> SupportResistanceZone | None:
        """Return the nearest support zone at or below price, including zones containing current price."""
        eligible = [zone for zone in zones if zone.lower_price <= latest_close]
        if not eligible:
            return None
        return min(eligible, key=lambda zone: zone.distance_from_price)

    @staticmethod
    def _nearest_resistance(zones: tuple[SupportResistanceZone, ...], latest_close: float) -> SupportResistanceZone | None:
        """Return the nearest resistance zone at or above price, including zones containing current price."""
        eligible = [zone for zone in zones if zone.upper_price >= latest_close]
        if not eligible:
            return None
        return min(eligible, key=lambda zone: zone.distance_from_price)

    @staticmethod
    def _build_summary(
        nearest_support: SupportResistanceZone | None,
        nearest_resistance: SupportResistanceZone | None,
        analyzed_swing_count: int,
        zone_tolerance: float,
    ) -> str:
        """Build a concise support/resistance status summary for GUI display and logs."""
        support_text = "nearest support unavailable"
        if nearest_support is not None:
            support_text = f"support {nearest_support.label} {nearest_support.lower_price:.2f}-{nearest_support.upper_price:.2f}"
        resistance_text = "nearest resistance unavailable"
        if nearest_resistance is not None:
            resistance_text = f"resistance {nearest_resistance.label} {nearest_resistance.lower_price:.2f}-{nearest_resistance.upper_price:.2f}"
        return (
            f"{support_text}; {resistance_text}; "
            f"analyzed {analyzed_swing_count} swings; zone tolerance {zone_tolerance:.2f}"
        )

    @staticmethod
    def _build_disabled_snapshot(
        market_snapshot: MarketDataSnapshot,
        analyzed_swing_count: int,
        zone_tolerance: float,
    ) -> SupportResistanceSnapshot:
        """Build a neutral snapshot when the support/resistance engine is disabled."""
        return SupportResistanceSnapshot(
            symbol=market_snapshot.symbol,
            timeframe=market_snapshot.timeframe,
            support_zones=(),
            resistance_zones=(),
            nearest_support=None,
            nearest_resistance=None,
            generated_at=datetime.now(timezone.utc),
            analyzed_swing_count=analyzed_swing_count,
            zone_tolerance_price=zone_tolerance,
            summary="Support/resistance engine disabled by configuration.",
        )
